"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# ======================================
# BASE DIR
# ======================================

BASE_DIR = Path(__file__).resolve().parent.parent

# ======================================
# ENV
# ======================================

load_dotenv(BASE_DIR / ".env", override=True)

# ======================================
# SECURITY
# ======================================

SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]

# ======================================
# APPLICATIONS
# ======================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',

    'main',
]

# ======================================
# MIDDLEWARE
# ======================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ======================================
# URLS
# ======================================

ROOT_URLCONF = 'app.urls'

# ======================================
# TEMPLATES
# ======================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ninoliani'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ======================================
# WSGI
# ======================================

WSGI_APPLICATION = 'app.wsgi.application'

# ======================================
# DATABASE
# ======================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ======================================
# PASSWORDS
# ======================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ======================================
# INTERNATIONALIZATION
# ======================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# ======================================
# STATIC
# ======================================

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'ninoliani']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ======================================
# EMAIL
# ======================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
CONTACT_EMAIL_TO = os.getenv("CONTACT_EMAIL_TO", EMAIL_HOST_USER)

# ======================================
# TURNSTILE
# ======================================

TURNSTILE_SITE_KEY = os.getenv("TURNSTILE_SITE_KEY", "")
TURNSTILE_SECRET_KEY = os.getenv("TURNSTILE_SECRET_KEY", "")

# ======================================
# SEO
# ======================================

SITE_URL = os.getenv("SITE_URL", "https://YOUR_DOMAIN").rstrip("/")

# ======================================
# DEFAULT PK
# ======================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
