# Generated by Django 5.2.14 on 2026-05-31 19:24

from django.db import migrations, models


def copy_product_categories(apps, schema_editor):
    Product = apps.get_model('main', 'Product')

    for product in Product.objects.exclude(category_id=None):
        product.categories.add(product.category_id)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.category'),
        ),
        migrations.RunPython(copy_product_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
