# Generated by Django 5.2.14 on 2026-06-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AddField(
            model_name='collection',
            name='greek_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/logos/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/images/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
