# Generated by Django 5.2.14 on 2026-06-02 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_collection_options_collection_greek_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeNewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_new_arrival', to='main.product')),
            ],
            options={
                'verbose_name': 'Homepage New Arrival',
                'verbose_name_plural': 'Homepage New Arrivals',
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
