# Generated by Django 5.2.14 on 2026-06-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homenewarrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenewarrival',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_new_arrivals', to='main.product'),
        ),
    ]
